grv=1;
vsp=0;
hsp=0;
is_attacking = false;
attackCooldown = room_speed * 2; // Cooldown between attacks (2 seconds)
attackTimer = attackCooldown;
direction = 0;
facingright = false;
hit_wall_left = false;
hit_wall_below = false;
teleport_complete = false;